### ISSUE TITLE
Why use it over verifyArithmetic?

### ISSUE THREAD

**Issue by Qumeric** [xBacked-DAO/reach-safe-math#1]
Hi guys

Did you consider using Reach verifyArithmetic option instead of this? See https://docs.reach.sh/ref-programs-appinit.html

If yes, what are the advantages of this approach?

**Comment by AwolDes** [comment]
@Qumeric very sorry we are only just seeing this. This package has been modified a lot, and I think that it is more appropriate to use `verifyArithmetic` instead.  This package does not add as much utility as I originally though unfortunately; Reach is too smart!
